version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo Packaging application...
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
