version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - mvn install -DskipTests=true
  build:
    commands:
      - echo Building the project...
      - mvn package -DskipTests=true

artifacts:
  files:
    - target/*.jar
